version: '3.8'

services:
  # MySQL
  mysql:
    image: mysql:8.0
    container_name: django-mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psecret"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Django приложение
  django-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    volumes:
      - .:/app
      - django-static:/app/staticfiles
      - django-media:/app/media
    environment:
      # Django Settings
      - SECRET_KEY=django-insecure-change-this-in-production
      - DEBUG=True
      - ALLOWED_HOSTS=*
      - CSRF_TRUSTED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000,http://89.110.122.115:3000
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - PYTHON_API_URL=http://10.0.70.2:8000
      - PYTHON_API_URL_FALLBACK=http://10.0.70.14:8000
    network_mode: "container:openvpn"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    command: sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"

  # Nginx
  webserver:
    image: nginx:alpine
    container_name: django-nginx
    volumes:
      - .:/app
      - django-static:/app/staticfiles
      - ./docker/nginx:/etc/nginx/conf.d
    network_mode: "container:openvpn"
    restart: unless-stopped

volumes:
  mysql_data:
  django-static:
  django-media:

networks:
  app-network:
    name: app-network
    driver: bridge
