version: '3.8'

services:
  openvpn-client:
    build:
      context: ./openvpn-client
      dockerfile: Dockerfile
    container_name: openvpn-client
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./config:/vpn:ro
    environment:
      - OPENVPN_CONFIG=/vpn/client.ovpn
      - OPENVPN_ARGS=
    restart: unless-stopped
    ports:
      - "8081:3000"
    networks:
      - app-network

  django-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    volumes:
      - .:/app
      - django-static:/app/staticfiles
      - django-media:/app/media
    environment:
      # Django settings
      - SECRET_KEY=django-insecure-change-this-in-production
      - DEBUG=True
      - ALLOWED_HOSTS=*
      - CSRF_TRUSTED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000,http://89.110.122.115:8081
      - DJANGO_PORT=3000
      # MySQL на бэкенде через VPN
      - DB_HOST=10.0.70.2
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      # Backend API через VPN
      - PYTHON_API_URL=http://10.0.70.2:8000
      - PYTHON_API_URL_FALLBACK=http://10.0.70.14:8000
    restart: unless-stopped
    depends_on:
      - openvpn-client
    network_mode: "service:openvpn-client"

networks:
  app-network:
    driver: bridge

volumes:
  django-static:
  django-media:
